### ISSUE TITLE
Vehicle Management Module

### ISSUE THREAD

**Issue by alpha-og** [RPL-ERP-CET/rpl_erp#62]
The Vehicle Management system provides a consolidated view of vehicle health, mileage trends, and upcoming renewals. It includes interfaces for data entry, alerts, reports, maintenance tracking, certification management, mileage monitoring, and lifecycle management.

### **FR-6.1: Vehicle Maintenance Tracking**
* **FR-6.1.1:** The system shall enable users to log detailed maintenance records for vehicles, including repair type, service center name, repair cost, and service date.
* **FR-6.1.2:** It shall support structured data entry for recurring services such as tire rethreading, oil replacements, brake checks, and other scheduled interventions.
* **FR-6.1.3:** Users shall be able to upload service-related documentation, such as scanned invoices and warranty reports, as part of the maintenance record.
* **FR-6.1.4:** The system shall proactively alert vehicle owners or designated personnel about impending maintenance based on mileage or time intervals.

### **FR-6.2: Certification and Document Management** (core functionality achieved by documents module)
* **FR-6.2.1:** The system shall allow input and tracking of all essential vehicular certifications including insurance policies, pollution control certificates, fitness reports, and vehicle registration details.
* **FR-6.2.2:** Automated renewal reminders shall be sent in advance of certificate expiration to ensure compliance and minimize operational risk.
* **FR-6.2.3:** Users shall be able to upload digital copies of all documents and download them on demand for verification, audit, or regulatory purposes.

### **FR-6.3: Mileage and Usage Monitoring**
* **FR-6.3.1:** The system shall provide interfaces for entering odometer readings and fuel consumption data after each trip or refueling session.
* **FR-6.3.2:** Based on the input data, the platform shall compute mileage automatically and notify users of any abnormal reduction patterns.
* **FR-6.3.3:** Monthly and cumulative mileage reports shall be generated for every registered vehicle and made available in downloadable format.

### **FR-6.4: Vehicle Lifecycle Management**
* **FR-6.4.1:** The system shall store core lifecycle metadata for each vehicle including date of procurement, manufacturer details, model number, and scheduled depreciation.
* **FR-6.4.2:** All R&M (Repair & Maintenance) expenses incurred over the lifespan of a vehicle shall be tracked and visualized for analysis.
* **FR-6.4.3:** Provisions shall be made to log resale evaluations, scrap decisions, and final disposal details to support full lifecycle documentation.

## Progress
 

 - [X] Schema: https://github.com/RPL-ERP-CET/rpl_erp/issues/45#issue-3703006990
 - [X] Task Groups: https://github.com/RPL-ERP-CET/rpl_erp/issues/63

**Comment by SreehariVinayan** [comment]
### This list captures issues, UX observations, and suggestions identified during Vehicle Module UI testing.
Checked items indicate completed fixes; unchecked items require follow-up.

- [x] **Row selection state not reset after delete**  
    After deleting a selected row, UI still shows “1 selected”.
    **Cause:** Cache not resetting after mutation.  

- [x] **Empty page state after deleting all records on a page**  
    If all records on a paginated page are deleted (e.g., page 2 of Vehicles), the UI stays on the same page and shows “no results found”.  
    There is no way to navigate to another page via the UI; only manually changing the `page` query param works.  
    **Expected behavior:** redirect to a valid page (e.g., previous page) or auto-adjust pagination after deletion.
   

- [x] **Delete confirmation dialog not shown in subsequent deletes**  
	In multiple pages, after performing a delete action, subsequent delete attempts do not show the confirmation dialog and the delete action becomes unusable. 
	**Impact:** user cannot perform further deletes without a refresh.  
	**Note:** seems to be a broader issue with delete action rather than a module-specific UX issue.
    
- [x]  **Service History – Optional Next Due Date fails on save**  
    Clearing _Next Due Date_ (marked optional) results in a “failed to {update/create} service history” error.  
    **Cause:** payload sends empty string instead of `null`; backend expects `Date | null`.  
       
- [x]  **Table horizontal scroll not accessible via mouse**  
    Tables don’t expose a visible horizontal scrollbar; right-side columns are hard to access without trackpad gestures or arrow keys.  
    
- [x] **Vehicle purchase date allows future dates**  
    While adding a vehicle, _purchase date_ accepts future dates. This seems unintended. A similar issue is observed for service date, tire retreading date and "next due date" (should not allow past dates)  
    
- <del> **Vehicle Type column not sortable** 
    The _Vehicle Type_ column does not have sorting enabled. Enabling it would align with other columns.</del>
    
- [x]  **Search not working due to missing backend config**
    Search param (`?search=...`) had no effect on results.  
    **Root cause:** `searchFields` not specified in `@FilterParams` for `Vehicle`.  
    
- [x]  **Service History – Cost field does not accept decimal values**  
    Editing service records with decimal cost shows warnings on save.  _(Screenshot attached)_

- <img width="300" height="300" alt="Image" src="https://github.com/user-attachments/assets/6a9d67bb-1532-4791-a75b-7f32b36dc121" />

        
- [x]  **Mileage log – Month field type mismatch**  
    Unable to add mileage log due to validation error: _expected number, received string_ for Month field.  
    Likely another form input normalization issue.  _(Screenshot attached)_
    
- <img width="300" height="300" alt="Image" src="https://github.com/user-attachments/assets/200cdb99-b7bf-4469-8a2e-71f2e7cb4e4c" />

- [x] **Form validation errors not brought into view on submit**  
    When creating/editing a record, if the user scrolls down to fill fields and submits the form, any validation error in a top (currently off-screen) field is not auto-scrolled into view.  
    This makes it unclear why the save action fails.  
    **UX suggestion:** auto-scroll / focus the first invalid field on submit.
    

- [x] **Deleting a service/vehicle type used by service/vehicle records shows no actionable feedback**  
	When attempting to delete a service/vehicle type that is referenced by an existing service/vehicle record, deletion is correctly blocked by the backend (foreign key constraint).  
	However, the UI only shows a generic “failed to delete” message, with no indication of _why_ the action failed.  This makes it unclear to the user what went wrong or how to resolve it.

- [x] **UX enhancement: Action menu on row right-click**  
    Suggestion to support a right-click (context menu) on a record row to surface row-level actions (e.g., view, edit, delete).  
    This could improve discoverability and reduce reliance on inline action buttons, especially for dense tables.  
    _Optional enhancement; not blocking._
- [x] **UX improvement: Explicit “Apply Filters” action**  
	When selecting filters, table contents update only after clicking outside the filter modal.  
	While this behavior works functionally, the lack of an explicit _Apply_ action can be confusing, as users may not realize when filters are applied.  
	**UX suggestion:** add an _Apply Filters_ button (or make the apply behavior explicit) to improve clarity and feedback._(Screenshot attached)_

- <img width="300" height="300" alt="Image" src="https://github.com/user-attachments/assets/b0d115ac-2e8d-4588-ac15-568be5fed963" />

**Comment by alpha-og** [comment]
> Delete confirmation dialog not shown in subsequent deletes
In multiple pages, after performing a delete action, subsequent delete attempts do not show the confirmation dialog and the delete action becomes unusable.
Impact: user cannot perform further deletes without a refresh.
Note: seems to be a broader issue with delete action rather than a module-specific UX issue.

I'm unable to reproduce this bug, perhaps the bug was resolved during the recent commits that fixed the cache invalidation bug, can you verify the same?

@SreehariVinayan

**Comment by SreehariVinayan** [comment]
@alpha-og , I re-tested on the latest commits and found a specific repro case.

Repro:
- Add a new record.
- Then try deleting any record.

Then the delete confirmation dialog does not appear and delete becomes unusable until refresh.
This doesn’t happen without the create step, which may be why it was hard to reproduce earlier.

**Comment by alpha-og** [comment]
I see, its likely that the create action may not be clearing the intent correctly. I'll look into it

**Comment by alpha-og** [comment]
@SreehariVinayan I have resolved most of the issues (the ones that have been checked). Let me know if they have completely fixed the issue and if there any more edge cases that need to be handled.

**Comment by SreehariVinayan** [comment]
@alpha-og,
#### Observations after fixes:

1. #### Date validation (partially resolved)
- The future-date restriction now works for vehicle purchase date and service date, but it still seems to be missing for tire retreading date.
Not sure if this is intentional, but flagging it in case the same constraint is expected here as well.

2. ####  Decimal cost validation not limited to Service History
- The issue where decimal values are not accepted for the cost field is also present in Mileage Logs and Vehicle Records, not just Service History.

3. #### Update – Service History: Next Due Date (partially resolved)
- Clearing the date now works correctly when editing an existing record.
However, when creating a new service history record, clearing the Next Due Date still prevents form submission.

The remaining fixes look good so far. I’ll comment here if I notice any additional issues.

**Comment by alpha-og** [comment]
I have addressed the all the issues except the following:

1. **Sorting by Vehicle Type** has not been added since it requires a slightly more complex filtering pattern as the filter must be applied on a nested query result because Vehicle Type becomes part of the query result after a JOIN operation.
2. Database error propagation (will be fixed shortly)

**Comment by alpha-og** [comment]
@SreehariVinayan Thank you for the detailed testing and feedback. Let me know if you happen to find more bugs and do verify that the most recently noted problems have also been fixed (I did some basic testing and it appeared to work).

**Comment by alpha-og** [comment]
I've added database error propagation in the latest commit. The ambiguous error message should be resolved now @SreehariVinayan

**Comment by SreehariVinayan** [comment]
@alpha-og, Few observations:

#### Numeric fields handling (fixed)

- Decimal values are now handled correctly for Mileage records (fuel, fuelCost) and Service records (cost).
- The issue still occurs for Vehicle purchaseCost and odometer-related fields in multiple places.
- This appears to be intentional based on the entity definitions. In *.entity.ts, these fields are defined as bigint, which does not support decimal values.
- Whether these fields should accept decimals or remain integer-only seems to be a design decision.

#### Mileage record – Month field (minor UX)

- The issue with saving the month field in mileage records is now fixed and works correctly.
- One minor UX issue remains: when editing an existing mileage record, the month field is not prefilled and appears blank, even though a value exists. _( Screenshot attached )_
- This doesn’t block functionality, but pre-filling the value would improve clarity and consistency with other fields.

- <img width="600" height="600" alt="Image" src="https://github.com/user-attachments/assets/d0a52c40-b5d6-4f72-87ea-52a542c5062e" />

#### Delete feedback for service / vehicle types in use (not fixed it seems)
- From a user perspective, there is still no actionable feedback. _( Screenshot attached )_
- No meaningful toast or message explains why the delete failed
- Since this is a valid constraint (the service / vehicle type is in use), it would be helpful to surface a clear, user-facing message (e.g., “This service type is currently in use and cannot be deleted”) instead of a generic failure.

- <img width="1411" height="600" alt="Image" src="https://github.com/user-attachments/assets/6dc2ce11-4eba-42db-bcad-e8bb7befb67b" />

- Note: While testing the delete flow for this issue (service/vehicle types that are still in use), the API responds with:
```
{
  "status": 400,
  "title": "BAD_REQUEST",
  "detail": "Referenced resource not found"
}
```

- This response seems misleading in this scenario, since the referenced records do exist.

I will let you know if I find anything else.

**Comment by alpha-og** [comment]
@SreehariVinayan I have extended the functionality of the filtering mechanism to support single level nested filters. The Vehicle Type filtering should be supported now. I have also fixed the month value not showing up (it was due to a type coercion misconfiguration). Can you look into the overall module functionality to make sure there are no regressions?

**Comment by alpha-og** [comment]
I have resolved the database error propagation inconsistencies by updating the dataview architecture and the server error handling for database errors. 

The concern regarding entity attribute types needs to be discussed since decimal does seem more appropriate for those fields.

**Comment by alpha-og** [comment]
@RohanAJacob2004 look into the functionality and implementations necessitated by each task group and mark the sub-tasks/ issues as completed once verified by EOD

**Comment by alpha-og** [comment]
@KK-8848 See to it that this module is reviewed and merged into dev by Wednesday.
